name: win

on:
  push:
    tags:
    - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Check environment
        run: |
          echo "Current Working Directory:" $PWD
          echo ${{ runner.workspace }}
          cd ${{ runner.workspace }}
          echo "Current Working Directory:" $PWD
        
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Verify MSBuild installation
        run: msbuild /version

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgArguments: 'boost libevent berkeleydb sqlite3 sqlcipher zeromq qt5 qt5-graphicaleffects qt5-quickcontrols'

      
