name: win

on:
  push:
    tags:
    - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [windows-2022, ubuntu-20.04, macos-12]
        #os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: '539a182d3773b9a84807b978c9684ba471446bf4'
          
      - name: Display vcpkg.json
        run: |
          find ${{ github.workspace }} -name "vcpkg.json" -print
          cat ${{ github.workspace }}/vcpkg.json

      
