name: Install vcpkg and C++ dependencies

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up vcpkg
        uses: microsoft/vcpkg-action@v11
        with:
          vcpkg-args: integrate install
